server:
  port: 80


spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/spider?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
     database: mysql
     show-sql: false
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect



config:
  keyVal: '#基金#'
  cookie: 'WEIBOCN_FROM=1110006030; SUB=_2A25NX5ShDeRhGeFK4lcR8SvJzTWIHXVuozzprDV6PUJbkdANLRatkW1NQtQNAzQ-xcS6YP54FHEI4LtwKUqFXRtN; _T_WM=94982254950; MLOGIN=1; XSRF-TOKEN=32def1; M_WEIBOCN_PARAMS=oid%3D4618594081834643%26lfid%3D4618594081834643%26luicode%3D20000174%26uicode%3D20000174'
  maxNum: 500
